//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

'use strict';

var AWS = require('aws-sdk'),
	uuid = require('uuid'),
	documentClient = new AWS.DynamoDB.DocumentClient();

exports.handler = function(event, context, callback) {
    var body = JSON.parse(event.body);

	var scanParams = {
		TableName: "pointventure-mobilehub-1424110637-families",
		FilterExpression: "#hc = :code",
		ExpressionAttributeNames: {
			"#hc": "hashedCode"
		},
		ExpressionAttributeValues: {
			 ":code": body.hashedCode
		}
	}
	documentClient.scan(scanParams, function(err, data) {
		if (err || data.Items.length == 0) {
			var response = {
				statusCode: 206,
				headers: {"Content-Type": "application/json"},
				body: JSON.stringify({"error" : "incorrect credentials, no such family"})
			};
			console.log("response: " + JSON.stringify(response))
			callback(err, response)
		} else {
			var family = data.Items[0]
    		var secondScanParams = {
				TableName: "pointventure-mobilehub-1424110637-individuals",
				FilterExpression: "#nm = :name",
				ExpressionAttributeNames: {
					"#nm": "name"
				},
				ExpressionAttributeValues: {
					 ":name": body.name
				}
			}
			documentClient.scan(secondScanParams, function(err, data) {
				if (err || data.Items.length == 0) {
					var response = {
						statusCode: 206,
						headers: {"Content-Type": "application/json"},
						body: JSON.stringify({"error" : "incorrect credentials, no such individual"})
					};
					console.log("response: " + JSON.stringify(response))
					callback(err, response)
				} else {
					if (family.individualKeys.includes(data.Items[0].primaryKey)) {
						var response = {
			                statusCode: 200,
			                headers: {"Content-Type": "application/json"},
			                body: JSON.stringify({
								"individual" : data.Items[0],
								"family" : family
							})
			            };
			            console.log("response: " + JSON.stringify(response))
						callback(null, response)
					} else {
						var response = {
							statusCode: 206,
							headers: {"Content-Type": "application/json"},
							body: JSON.stringify({"error" : "incorrect credentials, no such individual in this family"})
						};
						console.log("response: " + JSON.stringify(response))
						callback(err, response)
					}
				}
			});
		}
	});
};
