//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

'use strict';

var AWS = require('aws-sdk'),
	uuid = require('uuid'),
	documentClient = new AWS.DynamoDB.DocumentClient();

exports.handler = function(event, context, callback) {
    var body = JSON.parse(event.body);

    var parent = {
		Item : {
			"primaryKey" : uuid.v1(),
			"points" : 750,
			"displayName" : body.parentDisplayName,
			"imageURL" : "None",
			"isParent" : true,
			"name" : body.parentName
		},
		TableName : "pointventure-mobilehub-1424110637-individuals"
	};

	documentClient.put(parent, function(err, data) {
	    if (err) {
    		var response = {
                statusCode: 500,
                headers: {"Content-Type": "application/json"},
                body: JSON.stringify({"error" : "could not enter parent into SQL database"})
            };
            console.log("response: " + JSON.stringify(response))
			callback(err, response)
	    } else {
	        var family = {
	            Item : {
	                "primaryKey" : uuid.v1(),
	                "points" : 1000,
	                "name" : body.familyName,
	                "hashedCode" : body.hashedCode,
	                "manualOverrideEnabled" : body.manualOverrideEnabled,
	                "individualKeys" : [parent.Item.primaryKey],
	                "imageURL" : "None"
	            },
	            TableName : "pointventure-mobilehub-1424110637-families"
	        }
	        documentClient.put(family, function(err, data) {
        	    if (err) {
            		var response = {
                        statusCode: 500,
                        headers: {"Content-Type": "application/json"},
                        body: JSON.stringify({"error" : "could not enter family into SQL database, parent was entered"})
                    };
                    console.log("response: " + JSON.stringify(response))
					callback(err, response)
        	    } else {
            		var response = {
                        statusCode: 200,
                        headers: {"Content-Type": "application/json"},
                        body: JSON.stringify({"individual" : parent.Item, "family" : family.Item})
                    };
                    console.log("response: " + JSON.stringify(response))
					callback(null, response)
        	    }
	        });
	    }
	});

};
