//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

'use strict';

var AWS = require('aws-sdk'),
	uuid = require('uuid'),
	documentClient = new AWS.DynamoDB.DocumentClient();

exports.handler = function(event, context, callback) {
    var body = JSON.parse(event.body);
	var points = 0
	if (body.isParent) {
		points = 750
	} else {
		points = 500
	}
    var user = {
		Item : {
			"primaryKey" : uuid.v1(),
			"points" : points,
			"displayName" : body.displayName,
			"imageURL" : "None",
			"isParent" : body.isParent,
			"name" : body.name
		},
		TableName : "pointventure-mobilehub-1424110637-individuals"
	};

	documentClient.put(user, function(err, data) {
	    if (err) {
    		var response = {
                statusCode: 500,
                headers: {"Content-Type": "application/json"},
                body: JSON.stringify({"error" : "could not enter user into SQL database"})
            };
            console.log("response: " + JSON.stringify(response))
			callback(err, response)
	    } else {
	        var scanParams = {
                TableName: "pointventure-mobilehub-1424110637-families",
			    FilterExpression: "#hc = :code",
			    ExpressionAttributeNames: {
			        "#hc": "hashedCode",
			    },
			    ExpressionAttributeValues: {
			         ":code": body.hashedCode
			    }
	        }
	        documentClient.scan(scanParams, function(err, data) {
        	    if (err) {
            		var response = {
                        statusCode: 206,
                        headers: {"Content-Type": "application/json"},
                        body: JSON.stringify({"error" : "could not find family specified by hashedCode"})
                    };
                    console.log("response: " + JSON.stringify(response))
					callback(err, response)
        	    } else {
					var family = data.Items[0]
					var familyKey = data.Items[0].primaryKey
					var updateParams =  {
						TableName:"pointventure-mobilehub-1424110637-families",
					    Key:{
					        "primaryKey": familyKey,
							"points" : data.Items[0].points
					    },
					    UpdateExpression: "set individualKeys = :a",
					    ExpressionAttributeValues:{
					        ":a": data.Items[0].individualKeys.concat([user.Item.primaryKey])
					    },
					    ReturnValues:"UPDATED_NEW"
					}
					family.individualKeys = data.Items[0].individualKeys.concat([user.Item.primaryKey])
					documentClient.update(updateParams, function(err, data){
						if (err) {
							var response = {
								statusCode: 500,
								headers: {"Content-Type": "application/json"},
								body: JSON.stringify({"error" : "could not update information of family"})
							};
							console.log("response: " + JSON.stringify(response))
							callback(err, response)
						} else {
							var response = {
								statusCode: 200,
								headers: {"Content-Type": "application/json"},
								body: JSON.stringify({"individual" : user.Item, "family":family})
							};
							console.log("response: " + JSON.stringify(response))
							callback(null, response)
						}
					});
        	    }
	        });
	    }
	});

};
